# Generated by Django 2.1 on 2018-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created', models.DateField(auto_now_add=True)),
                ('time_spent', models.CharField(max_length=64)),
                ('learned', models.TextField()),
                ('resourses', models.TextField()),
            ],
        ),
    ]
